<?php



if( function_exists('acf_add_local_field_group') ):
	$choices = array();
	$choices['z'] = 'Zuchy';
	$choices['h'] = 'Harcerze';
	$choices['hs'] = 'Harcerze Starsi';
	$choices['w'] = 'Wędrownicy';

	acf_add_local_field_group(array(
		'key' => 'group_5cdf32a123acd',
		'title' => 'Użytkownik',
		'fields' => array(
			// array(
			// 	'key' => 'field_5cdf32ab63ea2',
			// 	'label' => 'Metodyka',
			// 	'name' => 'metodyka',
			// 	'type' => 'checkbox',
			// 	'instructions' => '',
			// 	'required' => 0,
			// 	'conditional_logic' => 0,
			// 	'wrapper' => array(
			// 		'width' => '',
			// 		'class' => '',
			// 		'id' => '',
			// 	),
			// 	'choices' => array(
			// 		'z' => 'Zuchy',
			// 		'h' => 'Harcerze',
			// 		'hs' => 'Harcerze Starsi',
			// 		'w' => 'Wędrownicy',
			// 	),
			// 	'allow_custom' => 0,
			// 	'default_value' => array(
			// 	),
			// 	'layout' => 'vertical',
			// 	'toggle' => 0,
			// 	'return_format' => 'value',
			// 	'save_custom' => 0,
			// ),
			array(
				'key' => 'field_5cdf3c38deaaa',
				'label' => 'Wybrana metodyka',
				'name' => 'wybrana_metodyka',
				'type' => 'select',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => $choices,
				'default_value' => array(
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'user_form',
					'operator' => '==',
					'value' => 'all',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
	));

	acf_add_local_field_group(array(
		'key' => 'group_5ccbf874bb224',
		'title' => 'Test',
		'fields' => array(

		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'draka',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
	));

acf_add_local_field_group(array(
	'key' => 'group_5c75d45e3e5c7',
	'title' => 'Draka - pytanie',
	'fields' => array(
		array(
			'key' => 'field_5ccbf87da41c8',
			'label' => 'Punkty',
			'name' => 'punkty',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'table',
			'sub_fields' => array(
				array(
					'key' => 'field_5ccbf8a4a41c9',
					'label' => 'Mnożnik Z',
					'name' => 'mnoznik_z',
					'type' => 'number',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'min' => '1',
					'max' => '25',
					'step' => '1',
				),
				array(
					'key' => 'field_5ccbf8d45e6f5',
					'label' => 'Mnożnik H',
					'name' => 'mnoznik_h',
					'type' => 'number',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'min' => '1',
					'max' => '25',
					'step' => '1',
				),
				array(
					'key' => 'field_5ccbf8e05e6f6',
					'label' => 'Mnożnik HS',
					'name' => 'mnoznik_hs',
					'type' => 'number',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'min' => '1',
					'max' => '25',
					'step' => '1',
				),
				array(
					'key' => 'field_5ccbf8ea5e6f7',
					'label' => 'Mnożnik W',
					'name' => 'mnoznik_w',
					'type' => 'number',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'min' => '1',
					'max' => '25',
					'step' => '1',
				),
			),
		),
		array(
			'key' => 'field_5c75d596e29ae',
			'label' => 'Odpowiedzi',
			'name' => 'odpowiedzi',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'table',
			'button_label' => '',
			'sub_fields' => array(
				array(
					'key' => 'field_5c75d7f2bda7a',
					'label' => 'Treść odpowiedzi',
					'name' => 'tresc_odpowiedzi',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => '',
					'new_lines' => '',
				),

				array(
					'key' => 'field_5c75d800bda82',
					'label' => 'Podpowiedź pytania',
					'name' => 'podpowiedz_pytania',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5c75d7ffbda81',
					'label' => 'Ilość punktów za pytanie',
					'name' => 'ilosc_punktow_za_pytanie',
					'type' => 'number',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '1',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'min' => '',
					'max' => '',
					'step' => '1',
				),
				array(
					'key' => 'field_5c75d7ffbda80',
					'label' => 'Obowiązkowe Z',
					'name' => 'obowiazkowe_z',
					'type' => 'select',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '1',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'brak' => 'Brak',
						'alfa' => 'Alfa',
						'beta' => 'Beta',
						'gamma' => 'Gamma',
						'delta' => 'Delta',
					),
					'default_value' => array(
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_5c75d7febda7f',
					'label' => 'Obowiązkowe H',
					'name' => 'obowiazkowe_h',
					'type' => 'select',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '1',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'brak' => 'Brak',
						'alfa' => 'Alfa',
						'beta' => 'Beta',
						'gamma' => 'Gamma',
						'delta' => 'Delta',
					),
					'default_value' => array(
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_5c75d7fdbda7e',
					'label' => 'Obowiązkowe HS',
					'name' => 'obowiazkowe_hs',
					'type' => 'select',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '1',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'brak' => 'Brak',
						'alfa' => 'Alfa',
						'beta' => 'Beta',
						'gamma' => 'Gamma',
						'delta' => 'Delta',
					),
					'default_value' => array(
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_5c75d7fcbda7d',
					'label' => 'Obowiązkowe W',
					'name' => 'obowiazkowe_w',
					'type' => 'select',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '1',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'brak' => 'Brak',
						'alfa' => 'Alfa',
						'beta' => 'Beta',
						'gamma' => 'Gamma',
						'delta' => 'Delta',
					),
					'default_value' => array(
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'draka',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5c5080486ba09',
	'title' => 'Instruktorzy',
	'fields' => array(
		array(
			'key' => 'field_5c50804df644c',
			'label' => 'Stopień instruktorski',
			'name' => 'stopien_instruktorski',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'brak' => '-',
				'pwd' => 'Przewodnik',
				'phm' => 'Podharcmistrz',
				'hm' => 'Harcmistrz',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c50809df644d',
			'label' => 'Imię',
			'name' => 'imie',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c5080a4f644e',
			'label' => 'Nazwisko',
			'name' => 'nazwisko',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c5080b0f644f',
			'label' => 'E-mail',
			'name' => 'e-mail',
			'type' => 'email',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'instruktorzy',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

endif;
